### ISSUE TITLE
How to identify the uuid from socket connection?

### ISSUE THREAD

**Issue by moksh-samespace** [amigniter/mod_audio_stream#10]

**Comment by amigniter** [comment]
You'll probably want to look for `Unique-ID` when listening for events on a socket connection. Described [here](https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Dialplan/Channel-Variables_16352493/#info-application-variable-names-variable_xxxx)

**Comment by moksh-samespace** [comment]
So the socket connection where we get the audio buffer and the one where we will get unique id will be the same?
