### ISSUE TITLE
if it run  with execute_on_media ,it will crash.

### ISSUE THREAD

**Issue by herbiel** [amigniter/mod_audio_stream#11]
originate {origination_uuid=a3dc8582-2966-4b91-a9d7-1b1054740dbd,api_on_media='uuid_audio_stream a3dc8582-2966-4b91-a9d7-1b1054740dbd start ws://localhost:8000 mono 8000 a3dc8582-2966-4b91-a9d7-1b1054740dbd'}sofia/external/sip:654321@192.168.51.71:5080 park inline

like this ,can you help check ?

**Comment by amigniter** [comment]
Of course, thanks for pointing out.

Can you tell me what happens, does it crash? (which shouldn't normally happen) or it is just not working in the way you want it.

I did a quick test here (uuid of course, needs to be created first, `create_uuid`):

`originate {origination_uuid=ae16c44e-dd62-4f89-b21c-194d45e90636,api_on_media='uuid_audio_stream ae16c44e-dd62-4f89-b21c-194d45e90636 start ws://192.168.0.30:3001 mono 8000'}sofia/internal/sip:1000@192.168.0.16:5061 park inline`

and there are no problems, works as expected.

**Comment by herbiel** [comment]
i have install the [mod_audio_stream](https://github.com/amigniter/mod_audio_stream) fs :(192.168.51.71)
freeswitch@debian11-freeswitch> originate {origination_uuid=ae16c44e-dd62-4f89-b21c-194d45e90636,api_on_media='uuid_audio_stream ae16c44e-dd62-4f89-b21c-194d45e90636 start ws://[192.168.51.71:8000](http://192.168.51.71:8000/) mono 8000'}sofia/internal/[sip:654321@192.168.50.16:15888](http://sip:654321@192.168.50.16:15888/) park inline

Socket interrupted, bye!

and the websocket server [192.168.51.71:8000](http://192.168.51.71:8000/) can't get any info.



the other side freeswitch([192.168.50.16:15888](http://192.168.50.16:15888/)),this is the diaplan

<extension name="public_extensions">

      <condition field="destination_number" expression="^(654321)$">

        <action application="pre_answer"/>

        <action application="playback" data="tone_stream://%(2000,4000,440,480)"/>

        <action application="bridge" data="user/1000"/>

      </condition>

</extension>



can you help test it ?

**Comment by amigniter** [comment]
ok, it's debian 11. I will see what's going on in this scenario when I get a little time.
`Socket interrupted, bye!` this shouldn't happen!!
i will get back once i check this.

**Comment by herbiel** [comment]
Okay thanks

**Comment by amigniter** [comment]
Interesting thing! But it is not a bug in the module but rather a matter of finding the most effective approach to achieve your desired outcome. We need to have an active session/channel. Methods like `api_on_media` or `api_on_pre_answer` are not a way to go.
You will have to use `api_on_answer` so we have the session answered and the API doesn't start too early. This way everything works as expected.

**Comment by herbiel** [comment]
yes,i just can't understand why it crash on api_on_media,or we can't change ?or can you tell me what's code make it crash,i use gdb to debug freeswitch,just only show :
Thread 52 "freeswitch" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff77e38700 (LWP 506401)]
0x00007ffff5995a1c in start_capture () from /usr/local/freeswitch/lib/freeswitch/mod/mod_audio_stream.so
and from the freeswitch log ,just crash on mod_audio_stream.c:75 calling stream_session_init.

**Comment by amigniter** [comment]
When `api_on_media` is used, and channel is in `pre_answer` state we don't have fully established channel and media.. api is called immediately, and we only have `uuid`, not a fully established channel yet, it's in the pre-answer state.

**Comment by herbiel** [comment]
i have add audio_stream app on your code ,but still crash,so can i make it work on pre_answer ?

SWITCH_STANDARD_APP(audio_stream_function)
{
    switch_status_t status = SWITCH_STATUS_FALSE;
    char wsUri[MAX_WS_URI] = "ws://localhost:8000";
    int sampling = 8000;
    switch_media_bug_flag_t flags = SMBF_READ_STREAM;
    char *metadata = switch_core_session_get_uuid(session);
    status = start_capture(session, flags, wsUri, sampling, metadata);
    if (status == SWITCH_STATUS_SUCCESS) {
         switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(session), SWITCH_LOG_ERROR,
                                      "websocket success info: %s\n", metadata);
    } else {
         switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(session), SWITCH_LOG_ERROR,
                                      "websocket fail info: %s\n", metadata);
    }
}

**Comment by amigniter** [comment]
Modifying it for the app instead of api can be done easily but it won't help you to achieve what you want to do. I explained in my previous comment that established channel is required. When you use api_on_media, it allows sending ringing or 183/sdp, and the channel is still in the early state (no media stream is established yet). So to speak, here the call is still at the SIP level and we need a fully established channel, with media, codecs.. so the module can attach the media bug to the channel and stream the audio frames to websocket.

**Comment by herbiel** [comment]
it's possible to make it support on media ?
