### ISSUE TITLE
if i get channel,it will crash after hangup? can you help me ?

### ISSUE THREAD

**Issue by herbiel** [amigniter/mod_audio_stream#16]
void eventCallback(notifyEvent_t event, const char* message) {
        switch_core_session_t* psession = switch_core_session_locate(m_sessionId.c_str());
        switch_channel_t* channel = switch_core_session_get_channel(psession);

**Comment by amigniter** [comment]
@herbiel Of course, buy you'll need to explain what you are trying to do. This section of code, are you trying to modify the original code and use some of your own code? 
If that's the case then when obtaining the session from FS you need to make sure it is valid:
`switch_core_session_t* psession = switch_core_session_locate(m_sessionId.c_str());
if(psession) {
  //your code goes here
  switch_core_session_rwunlock(psession);
}
`
If that is what you were doing after getting a session (and a channel from it) you **MUST** unlock the session. It can lead to a crash if not properly handled.

**Comment by herbiel** [comment]
OKay ,thank you,it has been solved.
