### ISSUE TITLE
Compiling in Docker

### ISSUE THREAD

**Issue by dwilkie** [amigniter/mod_audio_stream#18]
Hi,

I'm trying to compile this in Docker with the following Dockerfile, but I get the following errors:

```docker
FROM drachtio/drachtio-freeswitch-base as build

RUN cd /tmp && \ 
        git clone https://github.com/amigniter/mod_audio_stream && \ 
        cd mod_audio_stream && \
        git submodule init && \
        git submodule update && \ 
        mkdir -p build && \
        cd build && \
        cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_INCLUDE_DIR=/usr/lib/x86_64-linux-gnu/ -DZLIB_INCLUDE_DIR=/usr/lib/x86_64-linux-gnu/ ..
```

And It returns the following error 

```
CMake Error at CMakeLists.txt:23 (add_library):
  Target "mod_audio_stream" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at libs/IXWebSocket/CMakeLists.txt:174 (add_library):
  Target "ixwebsocket" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at libs/IXWebSocket/CMakeLists.txt:174 (add_library):
  Target "ixwebsocket" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Any ideas?

**Comment by amigniter** [comment]
Hi David,

This is what you can try. You need to modify CMakeLists.txt a little for Docker:
at line 9 add:
`find_package(Threads REQUIRED)`

the modify link_libraries like this:
`
target_link_libraries(mod_audio_stream PRIVATE Threads::Threads)
target_link_libraries(mod_audio_stream PRIVATE PkgConfig::FreeSWITCH)
target_link_libraries (mod_audio_stream PRIVATE ixwebsocket)
`
Also not sure what  the docker base image is, but at RUN commands where build-essential is (if its Debian), cmake and other tools, try adding `libpthread-stubs0-dev`. pthread support is required, looks like it's not found in the system.

**Comment by amigniter** [comment]
@dwilkie Is it compiling in Docker now?

**Comment by amigniter** [comment]
Well, they both have the same purpose but they're based on different websocket libraries. I wanted a small, efficient and a module I can fully control and I know completely inside out, that's how mod_audio_stream is created.
From a user's perspective , there are no major differences and they both work just fine although they are technically different.
When you test mod_audio_fork, can you log the size of incoming packets (on websocket endpoint), the size of audio chunks.
