### ISSUE TITLE
Unable to install for FreeSWITCH which compiled from source

### ISSUE THREAD

**Issue by hnimminh** [amigniter/mod_audio_stream#2]
Hi @amigniter 
I found your repo, it look interesting,. when trying to install this in FreeSWITCH which compiled from source, it failed. 
Could you please add installation guide for above case, where FreeSWITCH install on customized directory

Thanks

**Comment by amigniter** [comment]
cmake requires _pkg-config_ to find FS libs/directories. All you have to do is to provide path to FS custom **pkgconfig** directory (e.q. /usr/local/freeswitch is your custom installation path):
`export PKG_CONFIG_PATH=/usr/local/freeswitch/lib/pkgconfig/`
you can test it afterwards with:
`pkg-config --libs freeswitch`
Then you can proceed with build instructions.

**Comment by hnimminh** [comment]
now another error:
```
build# cmake -DCMAKE_BUILD_TYPE=Release ..
-- Checking for module 'freeswitch'
--   Found freeswitch, version 1.10.9-release
FreeSWITCH modules dir: /usr/local/freeswitch/mod
CMake Error at CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /usr/src/libs/mod_audio_stream/libs/IXWebSocket

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:18 (set_target_properties):
  set_target_properties Can not find target to add properties to: ixwebsocket


-- Configuring incomplete, errors occurred!
```

**Comment by amigniter** [comment]
I see. From the main folder please  do `git submodule init` and `git submodule update`.

**Comment by hnimminh** [comment]
work! thanks
