### ISSUE TITLE
Needed help Error during loading the module in FreeSWITCH 

### ISSUE THREAD

**Issue by qaissikandar** [amigniter/mod_audio_stream#21]
I am trying to load the module in freeswitch but am facing an issue with the symbol.

**/usr/local/freeswitch/mod/mod_audio_stream.so: undefined symbol: stream_session_pauseresume**

**Comment by amigniter** [comment]
@qaissikandar Please include your linux distribution. There was probably something strange when building the module.

**Comment by qaissikandar** [comment]
@amigniter 
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Comment by amigniter** [comment]
Did you follow installation instructions and also installed all the required dependencies? I am sure you did, module can't be built without them, but still a restart can help and also rebuilding the module. You can try with removing libfreeswitch-dev, install pkg-config and then install libfreeswitch-dev again, and rebuild the module. There is nothing wrong with the module but rather something strange with your build environment. Try it out please and let me know how it went.

**Comment by qaissikandar** [comment]
@amigniter I have tried the above response but it still same issue
I have removed and reinstalled the libfreeswitch-dev. One thing I want to mention I have installed this in the mod/application. is there any issue with that?
