### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by gregoriusus** [amigniter/mod_audio_stream#22]
Is it possible to build module in Visual studio in windows as freeswitch does?

**Comment by amigniter** [comment]
No, this module is currently designed for Linux only. However, the code itself should be platform-independent, so it's likely that it could be compiled on Windows with some adjustments to the build system.

To adapt the CMakeLists.txt file for Windows, you'll need to make changes to accommodate differences in toolchains, paths, and dependencies. Unfortunately I don't have personal experience with developing in a Windows environment but for someone who does it wouldn't be much a problem to adapt the CMake.
