### ISSUE TITLE
Switch Crash from CLI

### ISSUE THREAD

**Issue by murugancmi** [amigniter/mod_audio_stream#28]
OS : Debian 12((bookworm))

Freeswitch version: 1.10.1

Issue:  When I execute the bellow command from the CLI 

freeswitch@ind-switch-mumbai> uuid_audio_stream cd72e54f-feca-4933-8960-5e6504feab9e start ws://telecmi.ngrok.io mono
Socket interrupted, bye!

Error Result: Segmentation fault (core dumped)

**Comment by amigniter** [comment]
Oh, I see.. thanks for reporting this. It is a bug indeed and it occurs only when the sampling rate parameter is omitted from the command line (8k or 16k). It is now fixed, and if omitted, default value will be 8k. It didn't affect functionality in any way.

(Make sure to provide port number to WS URI when calling the API, unless you are hitting default 80|443).

**Comment by murugancmi** [comment]
don't you think, if the URL is not valid freeswitch crash is a big issue

**Comment by amigniter** [comment]
> hope it was fixed in the last commit.

Yes, it is fixed. 
BR.

**Comment by murugancmi** [comment]
Yes it's working, Thanks for the wonderful FreeSWITCH module

**Comment by amigniter** [comment]
@murugancmi You're welcome mate! All the best!
