### ISSUE TITLE
if centos7  can do this?

### ISSUE THREAD

**Issue by a00147600** [amigniter/mod_audio_stream#3]
My system is centos7.  And I had installed and meet this error.

freeswitch@localhost.localdomain> load mod_audio_stream
+OK Reloading XML
-ERR [module load file routine returned an error]

2023-08-09 16:32:26.795988 98.90% [INFO] switch_stun.c:896 External ip address detected using STUN: 122.228.134.190
2023-08-09 16:32:27.039581 98.90% [INFO] switch_stun.c:896 External ip address detected using STUN: 122.228.134.190
2023-08-09 16:32:27.218248 98.90% [INFO] mod_enum.c:884 ENUM Reloaded
2023-08-09 16:32:27.218248 98.90% [CRIT] switch_loadable_module.c:1754 Error Loading module /usr/local/freeswitch/lib/freeswitch/mod/mod_audio_stream.so
**/usr/local/freeswitch/lib/freeswitch/mod/mod_audio_stream.so: undefined symbol: is_valid_utf8**
2023-08-09 16:32:27.218248 98.90% [INFO] switch_time.c:1433 Timezone reloaded 1750 definitions
freeswitch@localhost.localdomain> 

I don't know how to solve. Any suggestion is useful .Thank you.

**Comment by amigniter** [comment]
Is your FS built and installed from source? If so, please take a look at [this](https://github.com/amigniter/mod_audio_stream/issues/2)
No sure what exactly caused the issue, but the path from loading module looks weird
`Error Loading module /usr/local/freeswitch/lib/freeswitch/mod/mod_audio_stream.so`

If FreeSWITCH is at custom location like /usr/local/freeswitch modules should be in /usr/local/freeswitch/mod directory. Please check what `pkg-config --libs freeswitch` returns. If not in path, export PKG_CONFIG_PATH and rebuild the module (make sure to init the submodule after cloning the repo). I will update the main readme file for users with FS at custom location.

**Comment by a00147600** [comment]
My installation method is as follows
Add mod name in /usr/local/src/freeswitch/modules.conf
Add mod folder in /usr/local/src/freeswitch/src/mod
cd /usr/local/src/freeswitch  execute make make install
sorry it's been a long time to reply. I followed the steps above to installed another mod.

**Comment by a00147600** [comment]
Following this method enabled me to successfully install.Thank u.
https://github.com/amigniter/mod_audio_stream/issues/2
I meet a new error and change a little code to successfully install.

audio_streamer_glue.cpp strncpy error
extern "C" {
    int validate_ws_uri(const char* url, char *wsUri) {
        // Regular expression to match a WebSocket URL
        std::regex regex("(wss?|ws)://[a-zA-Z0-9]+([\\-\\.]{1}[a-zA-Z0-9]+)*(:[0-9]+)?(/.*)?");

        if(std::regex_match(url, regex)) {
            strncpy(wsUri, url, MAX_WS_URI);
            return 1;
        }
        return 0;
    }
