### ISSUE TITLE
Stream Raw data with base64 encoded

### ISSUE THREAD

**Issue by Pandi1981** [amigniter/mod_audio_stream#36]
How to send the live stream from freeswitch with base64 encoded in json format... What kind of configuration required in freeswitch

**Comment by amigniter** [comment]
**mod_audio_stream** sends raw audio in a binary form, although it can accept `json` with base64 encoded audio. It is not difficult to modify the streamer to send b64 audio as well but we didn't plan such a feature, again, because each endpoint needs to recognize the format of a json object to be able to parse it. It could be more like a `custom` feature but as I said, not planned for the reasons mentioned.

**Comment by Pandi1981** [comment]
We could not able to send the live rtp stream when the call coming from drachtio sip recording server to freeswitch, but recording happening properly... Please help me in this...

**Comment by amigniter** [comment]
Will you please explain what exactly you want to achieve? You have incoming call from sip recording server, you can record it, but you can't send it again to next endpoint, is that correct?

**Comment by Pandi1981** [comment]
Yes correct

**Comment by amigniter** [comment]
Why don't you just use _mod_audio_stream_ to send it ? Does your `ws` endpoint require receiving b64 audio, you can't sent binary raw audio ?

**Comment by Pandi1981** [comment]
Yes I am using mod_audio_stream only with raw data  using uuid even though i send in some open source as well echo.Websocket not working... Shall I share freeswitch configuration.... If you make a call directly to freeswitch and it's working but the RTP stream comes from drachtio SRS not working

**Comment by amigniter** [comment]
yes, please share the config.

> but the RTP stream comes from drachtio SRS not working

This is to be expected. You also said when rtp stream comes to FS, you can record it ?

**Comment by Pandi1981** [comment]
<extension name="hairpin_and_record">
    <condition field="${sip_h_X-Return-Token}" expression="^(.+)$">
      <action application="export" data="sip_h_X-Return-Token=${sip_h_X-Return-Token}" />
      <action application="export" data="_nolocal_jitterbuffer_msec=100"/>
      <action application="set" data="RECORD_STEREO=true"/>
      <action application="set" data="call_id=${strftime(%Y%m%d_%H%M%S)}_${sip_from_tag}"/>
      <action application="set" data="outfile=$${base_dir}/recordings/${call_id}.wav"/>
      <action application="set" data="my_uuid=${uuid}" inline="true"/>
      <action application="set" data="STREAM_BUFFER_SIZE=500"/>
<action application="set" data="api_on_answer=uuid_audio_stream ${my_uuid} start wss://[echo.websocket.org](http://echo.websocket.org/) mixed 8k "/>



<action application="answer"/>
<action application="sleep" data="120000"/>
               
    </condition>
  </extension>

**Comment by Pandi1981** [comment]
<extension name="hairpin_and_record">
    <condition field="${sip_h_X-Return-Token}" expression="^(.+)$">
      <action application="export" data="sip_h_X-Return-Token=${sip_h_X-Return-Token}" />
      <action application="export" data="_nolocal_jitterbuffer_msec=100"/>
      <action application="set" data="RECORD_STEREO=true"/>
      <action application="set" data="call_id=${strftime(%Y%m%d_%H%M%S)}_${sip_from_tag}"/>
      <action application="set" data="outfile=$${base_dir}/recordings/${call_id}.wav"/>
      <action application="set" data="my_uuid=${uuid}" inline="true"/>
      <action application="set" data="STREAM_BUFFER_SIZE=500"/>
<action application="set" data="api_on_answer=uuid_audio_stream ${my_uuid} start wss://[echo.websocket.org](http://echo.websocket.org/) mixed 8k "/>



<action application="answer"/>
<action application="sleep" data="120000"/>
               
    </condition>
  </extension>

**Comment by amigniter** [comment]
> Please find the attachments yes I can able to record it!!!

Thank you. Yes, recording is fine. The issue you are facing when trying to stream the audio is that you are answering the channel (on api) and trying to stream using **mixed** mode but you only have single channel. In order to use mixed mode you need the B-leg as well, you need to bridge the channel and stream it in mixed mode.
To stream the current incoming call you can try using this command (since you only have A-leg)
`<action application="set" data="api_on_answer=uuid_audio_stream ${my_uuid} start wss://echo.websocket.org mono 8k "/>`

**Comment by Pandi1981** [comment]
Thanks a lot!!! 
It is working fine... 
Please help me how to send base64 encoded format... With json body

**Comment by amigniter** [comment]
You're welcome.

> Please help me how to send base64 encoded format... With json body

As I said, _mod_audio_stream_ sends L16 audio as a raw binary , not as b64 encoded. I might implement it as a feature but can't promise when.

**Comment by amigniter** [comment]
Please find b64_audio branch and checkout the branch to test this out.

You'll need to set the channel variable `STREAM_B64_AUDIO` to 1 or true. Once set when you start the streaming it will stream json object with base64 encoded audio instead of raw binary. Json object looks like this:
```json
{
    "audioDataType": "raw",
    "sampleRate": 8000,
    "channels": 1,
    "audioData": "base64 encoded audio..."
}
```

**Comment by Pandi1981** [comment]
Thanks a lot!!! 
Sorry for the another question... How to get a two audio file even though i am using single channel from drachtio... Please suggest me some idea please

**Comment by Pandi1981** [comment]
Because how to get caller and callee audio separately

**Comment by amigniter** [comment]
@Pandi1981 ,

> Sorry for the another question... How to get a two audio file even though i am using single channel from drachtio... Please suggest me some idea please

Unfortunately not possible with the module.

**Comment by Pandi1981** [comment]
I have changed the code for our required format... Please let me is this correct way... Or something wrong because receiver doesn't able to decode it... 

cJSON_AddStringToObject(jsonObject, "event", "media");
        cJSON* mediaObject = cJSON_CreateObject();
        cJSON_AddStringToObject(mediaObject, "payload", encodedAudio.c_str());
        cJSON_AddItemToObject(jsonObject, "media", mediaObject);

I have commended whatever you mentioned there!!!

**Comment by Pandi1981** [comment]
> @Pandi1981 ,
> 
> > Sorry for the another question... How to get a two audio file even though i am using single channel from drachtio... Please suggest me some idea please
> 
> Unfortunately not possible with the module.

Thanks a lot for your info!!!!

**Comment by Pandi1981** [comment]
Request json for your information
{
"event": "media",
"media": {
"payload": "base64_encoded_audio_data"
}

**Comment by amigniter** [comment]
> I have changed the code for our required format... Please let me is this correct way... Or something wrong because receiver doesn't able to decode it...
cJSON_AddStringToObject(jsonObject, "event", "media");
cJSON* mediaObject = cJSON_CreateObject();
cJSON_AddStringToObject(mediaObject, "payload", encodedAudio.c_str());
cJSON_AddItemToObject(jsonObject, "media", mediaObject);
I have commended whatever you mentioned there!!!

Looks correct to me for the required json object. You should inspect your ws endpoint then.
This is the method:
```c
void add_encoded_audio_json(cJSON* jsonObject, const char* audioData, size_t dataLength) {
    std::string encodedAudio = base64_encode(audioData, dataLength);

    cJSON* mediaObject = cJSON_CreateObject();

    cJSON_AddStringToObject(mediaObject, "payload", encodedAudio.c_str());

    cJSON_AddItemToObject(jsonObject, "media", mediaObject);

    cJSON_AddStringToObject(jsonObject, "event", "media");
}
```

**Comment by Pandi1981** [comment]
Thanks a lot!!! 
Anyidea how to decode what ever payload I am sending to wss server. 
Any opensoure to decode base64 encoded audio stream...

**Comment by amigniter** [comment]
It depends on the language your ws server is written in. I am sure you can find the b64 parser for it, just look for it.

**Comment by Pandi1981** [comment]
Hi bro
It's looks like some things wrong in our convertion. I have tried to decode the base64 encoded value in all the open source. Please check once again whether we need to add any padding at the end of each string like = or==

**Comment by Pandi1981** [comment]
https://conv.darkbyte.ru/

**Comment by amigniter** [comment]
@Pandi1981 
Ahh yes, you are right .. there was an error at the encoder. It is fixed now, tested and all looks correct. Please checkout the branch and try it out. You should apply your changes for the format of json object.

**Comment by Pandi1981** [comment]
Thanks a lot  ro!!! I am copying the libs files from main branch!!!

**Comment by Pandi1981** [comment]
In the raw data I can able to see g722.in and g722.out these input file used for streaming. Shall we use those in and out Read Write function I can send seperate stream with same url....

**Comment by Pandi1981** [comment]
What is the purpose of read and write in stream_frame function please.... I mean out_len>0

**Comment by Pandi1981** [comment]
I am sending extra parameter to construct start and stop notifications on the same socketid where the connection established!!!

#define STREAM_API_SYNTAX "<uuid> [start | stop | send_text | pause | resume | graceful-shutdown ] [wss-url | path] [mono | mixed | stereo] [8000 | 16000] [metadata] [stream_sid] [call_sid] [from] [to] [agentid]"
  const char* stream_sid = argv[6]; // stream_sid from command
                    const char* call_sid = argv[7]; // call_sid from command
                    const char* from = argv[8]; // from number from command
                    const char* to = argv[9]; // to number from command
                    const char* agentid = argv[10]; // agentid from command


status = start_capture(lsession, flags, wsUri, sampling, metadata, stream_sid, call_sid, from, to, agentid);
tech_pvt->stream_sid = strdup(stream_sid);
    tech_pvt->call_sid = strdup(call_sid);
    tech_pvt->wsUri = strdup(wsUri);
    tech_pvt->agentid = strdup(agentid);


For Live stream notification i have constructed and it sseems to be ok.

void add_encoded_audio_json(cJSON* jsonObject, const char* audioData, size_t dataLength,
                               uint32_t sampleRate, uint32_t channels, const char* wsUri, const char* agentId, const char* callSid) {
       
        std::string audioDataStr(reinterpret_cast<const char*>(audioData), dataLength);
        std::string encodedAudio = base64_encode(audioDataStr);

        cJSON_AddStringToObject(jsonObject, "event", "media");

        cJSON* mediaObject = cJSON_CreateObject();
        cJSON_AddStringToObject(mediaObject, "payload", encodedAudio.c_str());

        cJSON_AddItemToObject(jsonObject, "media", mediaObject);

     
        char url[1024];
        snprintf(url, sizeof(url), "%s/ecosmob/agent/%s/%s", wsUri, agentId, callSid);
        cJSON_AddStringToObject(jsonObject, "wssURL", url);
       
    }

Please guide me how to send the start and stop notifications on the same websocket URL with appending some extra parameter like this
wssurl/ecosmob/agent/agentid/call_Sid
agentid and call_sid will pass from input parameter

the above parameter need to append while sending start notifications for the wssURL
Request json
{
"event": "start",
"stream_sid": "unique_stream_id",
"sequence_number": "1",
"start": {
"stream_sid": "unique_stream_id",
"call_sid": "unique_call_id",
"from": "caller_phone_number",
"to": "receiver_phone_number",
"media_format": {
"encoding": "base64",
"sample_rate": "8000",
"bit_rate": "128kbps"}
}
}
In the above example while calling uuid_audio_stream we will pass the arguments
stream_sid
call_sid
from
to
agentid
based upon that we need to send send start notfications.

Please give me some idea please......

**Comment by Pandi1981** [comment]
How to send the jaon body in the  wsuri for start and stop notifications how to use the same websocket please help me

**Comment by amigniter** [comment]
Dear @Pandi1981,
I appreciate your interest in mod_audio_stream and the feature request for streaming base64 audio. I'm glad I could help by adding that functionality.

However, I must let you know that I am not in a position to provide extensive support beyond what has been implemented. As much as I'd like to assist further, my time is limited, and I am unable to work on custom use cases.

I recommend checking out the official documentation, forums, or communities related to FreeSWITCH for additional help and support. There are many knowledgeable people there who can assist you further.

Thank you for your understanding.

**Comment by Pandi1981** [comment]
Thanks a lot for your help!!!

**Comment by Pandi1981** [comment]
Much appreciated!!!
