### ISSUE TITLE
Send caller and callee audio in different websocket

### ISSUE THREAD

**Issue by Pandi1981** [amigniter/mod_audio_stream#45]
I am getting stereo with 2 channels.  Now how i can able to send  2 different websocket? I mean caller audio in one websocket and callee audio in another websocket. 
Please let me know your comments!!!

**Comment by amigniter** [comment]
When you are dealing with a connected call and using the mod audio stream, you have a couple of options for handling the audio streams for the caller and callee. The usage is explained on the main github page. Here’s a breakdown of the options:
### Option 1: Using Stereo or Mixed mode

**Separate Stereo Channels:**
- You can configure the mod audio stream to use the stereo option.
- In this setup, each participant (caller and callee) will be assigned to a separate stereo channel.
- For example, the caller’s audio could be on the left channel, and the callee’s audio could be on the right channel.
- This way, both participants are transmitted through a single WebSocket connection but are separated into distinct stereo channels.

**Mixed Mono Channel:**
- Alternatively, you can configure the mod audio stream to mix both participants’ audio into a single mono channel.
- In this case, both the caller and callee’s audio will be combined into one stream.
- This is useful if you do not need to separate the audio streams and prefer a simpler setup.

### Option 2: Using Separate WebSocket Connections
(This option is an answer to your question)
**Separate WebSocket Connections:**
- You can start a mod audio streamer on each participant's channel UUID.
- This means you will have two separate WebSocket connections, one for the caller’s audio and one for the callee’s audio.
- This setup allows you to stream each participant’s audio in parallel, ensuring that the streams are completely separate.

**Comment by Pandi1981** [comment]
Thanks a lot bro for your timely help!!! I learned so many things from you.

**Comment by Pandi1981** [comment]
I got the answer!!! Much appreciated....

**Comment by Pandi1981** [comment]
Thanks a lot!!!
