### ISSUE TITLE
Whether a deadlock exists ？

### ISSUE THREAD

**Issue by chinarui-na** [amigniter/mod_audio_stream#47]
when outbound call answer, i start  two media_bug, when call hangup, i found `show calls` still available call.
when don't use media_bug, it's fine.
i do not use c++, can u help me. thank you vary much.

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/7da9a8ca-9cf7-4d65-bc91-ba881e1efdc4">
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/17a78250-0834-4a84-bf6c-589b5442e946">

**Comment by chinarui-na** [comment]
#35 I got it back. The channel's still on

**Comment by chinarui-na** [comment]
The new code is fine

**Comment by remcovanvugt** [comment]
Got the same issue. Filed a PR

https://github.com/amigniter/mod_audio_stream/pull/62
