### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by jmordica** [amigniter/mod_audio_stream#59]
Any interest in making this a Debian package? It seems like this is the most used streaming module.

**Comment by eschmidbauer** [comment]
i think you would need to package the dependency `ixwebsocket` as well
best way to do this is find a debian maintainer who would be willing to sponsor it (throw them some $ for their time)

**Comment by jmordica** [comment]
I have confirmed that `ixwebsocket` can be added and I'll take care of funding it if this can be submitted.

Thanks!

**Comment by amigniter** [comment]
Yes, both the module and the websocket lib share compatible licenses. I find it is a very good idea, having a debian package. There is no problem for me creating it and I will put it here as a release (for debian 12).

**Comment by amigniter** [comment]
there is a debian 12 package under releases.

**Comment by amigniter** [comment]
Besides debian package which can be downloaded from `releases`, there is a README.debian in the main repository with instructions on how to add debian repo source and install the module from debian 12 bookworm.
The package is properly packed and created, lintian checked.
