### ISSUE TITLE
Socket interrupted, bye!

### ISSUE THREAD

**Issue by amsharinsky** [amigniter/mod_audio_stream#6]
Running the  uuid_audio_stream 971d5af3-24dc-4c88-8873-049ae005d559 start ws://localhost:8888 mono 8k command produces a Socket interrupted, bye! CentOS7 Freeswitch 1.10.10

**Comment by amigniter** [comment]
I am pretty sure that's not an audio_stream issue. Looks like it's much more serious issue cause fs_cli completely crashed. Is your FS installation working properly and mod_audio_stream properly built and installed? On a valid channel, even if there is no websocket server listening on specified port you should be able to run the api command which will give you an error and clean itself, but it will be working fine. Unfortunately your CLI is crashing. If you can provide some more details I will be happy to assist and solve the issue. You can restart FS and reload the module, and also test some other api command to make sure your installation is working fine. Try to originate a test call, uuid_broadcast, uuid_break to make sure it's all good. BR!

**Comment by amigniter** [comment]
Please refer to this [issue](https://github.com/amigniter/mod_audio_stream/issues/9#issue-1933349685) as it is all related to centos 7.
