### ISSUE TITLE
Not connecting to wss stream

### ISSUE THREAD

**Issue by jprangi** [amigniter/mod_audio_stream#63]
I am not able to setup a connection. This is what I am getting in the logs. Any idea how can I troubleshoot this? 

cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:00.769419 99.57% [DEBUG] sofia.c:7499 Channel sofia/internal/+9999999@192.168.0.26:5060 entering state [ready][200]
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.029359 99.57% [DEBUG] switch_rtp.c:7934 Correct audio ip/port confirmed.
2024-11-08 15:33:01.329382 99.57% [DEBUG] mod_audio_stream.c:150 mod_audio_stream cmd: 'cf182531-96bf-4176-8de3-30960d3dcef5' start wss://demo-support-tw.example.com/incomingconnection/6/46/59/cf182531-96bf-4176-8de3-30960d3dcef5 mono 8000
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] mod_audio_stream.c:81 calling stream_session_init.
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] audio_streamer_glue.cpp:348 cf182531-96bf-4176-8de3-30960d3dcef5: initializing buffer(320) to adjusted 512 bytes
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] audio_streamer_glue.cpp:376 (cf182531-96bf-4176-8de3-30960d3dcef5) no resampling needed for this call
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] audio_streamer_glue.cpp:379 (cf182531-96bf-4176-8de3-30960d3dcef5) stream_data_init
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] mod_audio_stream.c:87 adding bug.
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] switch_core_media_bug.c:978 Attaching BUG to sofia/internal/+1949999999@192.168.0.26:5060
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] mod_audio_stream.c:91 setting bug private data.
cf182531-96bf-4176-8de3-30960d3dcef5 2024-11-08 15:33:01.329382 99.57% [DEBUG] mod_audio_stream.c:94 exiting start_capture.

**Comment by amigniter** [comment]
Sorry for late reply. There shouldn't be any issues connecting to wss uri. I don't see a port provided in your api call. Without a port, wss method will try the port 443 as a default but if the websocket server is not running on that port it will not be able to connect. So make sure to provide a correct path to websocket server in your wss url, like wss://path-to-server.example.com:3000. Please reopen the issue if you still have problems.
