### ISSUE TITLE
Compilation for RHEL 9

### ISSUE THREAD

**Issue by spacetourist** [amigniter/mod_audio_stream#64]
This is not an issue, just a shout out for advice!

I'm working on getting this module built for FreeSWITCH running on EL9, I've given up on external compilation due to the lack of my ability to locate freeswitch-devel and so I'm trying to build it alongside FreeSWITCH.

C is not my language. Try as I might, I'm running into linking issues - any pointers at all would be a great help!

```
2024-11-13 16:52:00.773831 88.90% [CRIT] switch_loadable_module.c:1754 Error Loading module /usr/lib64/freeswitch/mod/mod_audio_stream.so
**/usr/lib64/freeswitch/mod/mod_audio_stream.so: undefined symbol: is_valid_utf8**
```

**Comment by amigniter** [comment]
That’s a way to go. Not totally sure about RHEL9 but isn’t there a rpm package freeswitch-devel (available for CentOS as well). Either way CmakeFile has to be adapted for appropriate packages for Red Hat or CentOS.

**Comment by spacetourist** [comment]
Thanks, I'm just glad to have completed the build - it took me a while :sweat_smile:  

I'm working on getting this app talking to OpenAI Relatime (one of many users trying this it seems) - I'm wondering how the events are expected to be used

If by returning streamAudio data I can generate a `mod_audio_stream::play` event, what is the best way to play this? Add a subscriber and execute some kind of playback to the FS API?

At present I have a Go app which starts the session, encodes and relays the audio stream to OAI and captures the B64 audio responses. I'm pursuing writing these to a temporary file for playback but wondered if I'm missing a trick with those events?

**Comment by hizbi-github** [comment]
@spacetourist Assuming your Golang app is the middleware between FreeSWITCH and OpenAI, you can send the WAV base64 from OpenAI in JSON through the Websocket connection back to FS and mod_audio_stream will write it to a temporary file + generate a event on ESL which contains the path to the temp audio file.

What we did was to trigger a simple Lua script on the "mod_audio_stream::play" custom event and then play audio from the WAV file created by mod_audio_stream.

We used "uuid_displace" to play the audio, as it allows you to overlap this audio over any background audio in the channel if any.

Do note that if you want to record the call, use the "f" flag at the end in the "uuid_displace" command, otherwise the audio played back by "uuid_displace" command will not be recorded.

**Comment by spacetourist** [comment]
Thanks for your response, I implemented a similar method however using playback i found that the service was not acting in realtime in the way I was hoping as the latency between complete media received and playback start was too long, especially for longer model responses.

My final implementation resolved this by creating new shoutcast endpoints for each incoming conversation item which I then used by having FS start the stream immediately when a new conversation item was active and closing that stream when an interruption occurs. This gave a superior experience and was useful for demo purposes however I have since discovered that there just isn't as much utility in the OAI Realtime service as there is on the "chained STT>LLM>TTS" approach. Fun as a tech demonstrator, but I'm parking this implementation until the next update from OAI!

**Comment by hizbi-github** [comment]
@spacetourist Oh that's cool, I didn't know you can stream the audio using mod_shout like this!

And yeah we used the STT>LLM>TTS approach with Deepgram, AWS Bedrock (Claude), and ElevenLabs.
We didn't notice any particular delay with the audio playback, other than the inherent delay in the STT>LLM>TTS process itself.

We were able to instantly interrupt the current audio playback using "uuid_displace start" and "uuid_displace stop" and play the latest audio as soon as "mod_audio_stream::play" event was emitted.

**Comment by spacetourist** [comment]
Great, I think your solution is the way to go for any useful implementation at this time - this avoids the limitations of relying on voice-voice adhering to its instructions! Plus it allows heaps more flexibility as you can swap out the components. Similar to you I have a separate implementation which is DeepGram STT>OpenAI assistant>DeepGram TTS - I'm going to revisit that and implement interruptions after this journey with Realtime API. Long term I expect the V2V models to be the correct implementation however its totally unusable for anything serious today.

Elevenlabs seem great - maybe I should move over to them for my TTS step, would you recommend? I presume it was chosen due to the better voices rather than any latency improvement?

I should note that my shout implementation was not production-serious - to make it work I was streaming the responses through ffmpeg to encode them as MP3 in near realtime, if the underlying API ever improves there is still scope for a neat little FS native module for actually accepting a stream of audio back in the formats produced by the API - sadly this wacky setup was the best I could do with the existing feature set in FreeSWITCH (which is certainly capable of a very clean implementation!)

**Comment by hizbi-github** [comment]
@spacetourist Yep!

And yes, the decision to use ElevenLabs instead of Deepgram for TTS was purely based on the voices they provide and the natural tone they have. They are pretty similar latency wise.

ElevenLabs does provide the TTS audio in WAV over its Websocket API, so we had very little overhead in sending it over to FS and playing it there, just needed to base64 encode it as that's what mod_audio_stream requires.

**Comment by spacetourist** [comment]
Hello there, just noticed that you've created the two way websocket stream
for the module, great work!

I'm happy to report that I'm getting great utility from the older module
version, no need for the bidirectional streaming right now but I'm sure
that'll change going forward.

Just figured I'd send you a note to say congrats, all the best 👍
