### ISSUE TITLE
Streaming audio and parallel enable recording in dialplan 

### ISSUE THREAD

**Issue by Pandi1981** [amigniter/mod_audio_stream#67]
When we are enabling recording in the dialplan we are not able to send the caller audio streaming, but connection established but after sometime connection got disconnected with 1006 abnormal closure...
In the dialplan we are set record-session..and lua script sending streaming.
Any suggestions please 
Note: both the channel call uuid is same...I mean recording and streaming access the same uuid

**Comment by Pandi1981** [comment]
Any update it will be well and good please!!!!
WSS streaming and recording we can not able to do it parallel!!!

**Comment by amigniter** [comment]
Unfortunately I cannot address every particular use case unless it is actually a bug. Are you sure record_session is causing a conflict? Try removing record_session to make sure streaming is fine and there is no disconnecting. Since you are using lua script to call the API, maybe you can also use `uuid_record` from the same lua script to record.

**Comment by Pandi1981** [comment]
Yes after removing the record_session it is working fine...
And also I tried in Lua script to use uuid_record before the streaming started not working.
After then i tried to use uuid_record after the straming started for channel_call_uuid & otherleg_call_uuid its working fine....
Looks like a strange behaiour
Please let me know if you need any freeswitch log i will share you...

Dial plan: once we commented the record-session, streaming is working a-lg and b-leg
  <action application="set" data="STREAM_B64_AUDIO=true"/>
        <action application="set" data="STREAM_BUFFER_SIZE=20"/>
        <action application="set" data="my_uuid=${uuid}" inline="true"/>
        <action application="set" data="sip_copy_custom_headers=true"/>
        <action application="set" data="sip_h_X-outbound-callid=${uuid}"/>
        <action application="set" data="export_vars=${sip_call_id}"/>
        <action application="set" data="customerno=${destination_number}" inline="true"/>
        <action application="set" data="sip_h_X-calltype=${sip_h_X-calltype}"/>
		    <action application="lua" data="variables.lua ${my_uuid}"/>
	<action application="set" data="outfile=$${base_dir}/recordings/${uuid}"/>
	
	<action application="set" data="api_on_answer=luarun stream_audio.lua ${my_uuid} ${sip_h_X-calltype} ${destination_number} ${sip_from_user} ${sip_h_X-agent_id} ${sip_h_X-callid} ${outfile}"/>

**Comment by amigniter** [comment]
> If uuid_record after the streaming in lua then
Recording working and B-leg streaming working & and A-leg Streaming working.

right. looks like the right option to start recording after you start the streaming.

**Comment by Pandi1981** [comment]
Yes correct!!!

**Comment by Pandi1981** [comment]
Issue resolved

**Comment by Pandi1981** [comment]
Working fine as we expected
