### ISSUE TITLE
streamAudio interception

### ISSUE THREAD

**Issue by murugancmi** [amigniter/mod_audio_stream#68]
Is there any way interception ongoing stream because when customer speak i need to interception on going coversation i mean ongoing base64 chunk

**Comment by amigniter** [comment]
Actually no, there is no way to intercept what is being streamed from the module to the websocket server; the chunks are sent either directly or through the buffer depending on the buffer size. It is sent as L16, meaning raw 16bit audio chunks.

You could intercept it though by setting up a middle man, your websocket server, which can intercept the received audio and forward it further. There you have full control of the audio.

**Comment by murugancmi** [comment]
OK even we can use in ESL ,to stop ongoing stream but the problem its pause current chunk ,if we add extra websocket server in between again its extra latency

**Comment by amigniter** [comment]
Right, I understand your request but unfortunately there is no other way around. You can't start two streams for example from the same channel. The module streams audio to websocket server, and access to the data is only available at the endpoint which is the websocket server. If you introduce a middleware websocket server, at the same server, the latency will be minimal. 

The audio sent to the websocket server could be saved to a file in parallel while being streamed (just an idea) which will give you access to it. It is beyond the actual purpose of the module but you could implement it very easily.

**Comment by murugancmi** [comment]
sure i will try thins and thanks
