### ISSUE TITLE
Crash Freeswitch by kernel 

### ISSUE THREAD

**Issue by phamhieptel4vn** [amigniter/mod_audio_stream#7]
I have install success and reload mod is working. Also, i run streaming to websocket and crash freeswitch. Log error:

Oct 3 11:43:13 pl-vmdpitel kernel: [479547.709584] freeswitch[26669]: segfault at 18 ip 00007f5f02691973 sp 00007f5e12001e80 error 4 in libpthread-2.28.so[7f5f0268d000+f000]
Oct 3 11:43:13 pl-vmdpitel kernel: [479547.712505] Code: 8d 3d c9 ac 00 00 e8 7c b8 ff ff 66 2e 0f 1f 84 00 00 00 00 00 66 90 41 56 41 55 41 54 49 89 fc 55 53 64 8b 2c 25 d0 02 00 00 <8b> 57 10 81 e2 7f 01 00 00 83 fa 23 7f 5f 83 fa 20 7d 78 83 fa 03

**Comment by amigniter** [comment]
Not sure if it happens on CentOS. Please try to rebuild the module with the latest update if it is [centos](https://github.com/amigniter/mod_audio_stream/issues/9#issue-1933349685)
